/**
 * A compact, dependency-free emoji catalog for the picker. Keywords are
 * lowercased so the picker can do case-insensitive substring matching.
 * Discord ships thousands; ~150 covers the 95% case for reactions.
 */
export interface EmojiEntry {
  e: string;
  k: string[];
}

export const EMOJI_CATALOG: EmojiEntry[] = [
  // Smileys & Reactions
  { e: "😀", k: ["grin", "smile", "happy"] },
  { e: "😁", k: ["beam", "grin"] },
  { e: "😂", k: ["joy", "laugh", "lol"] },
  { e: "🤣", k: ["rofl", "laugh"] },
  { e: "😃", k: ["smile", "happy"] },
  { e: "😄", k: ["smile", "happy"] },
  { e: "😅", k: ["sweat", "phew"] },
  { e: "😆", k: ["laugh"] },
  { e: "😉", k: ["wink"] },
  { e: "😊", k: ["blush", "smile"] },
  { e: "😋", k: ["yum", "tongue"] },
  { e: "😎", k: ["cool", "sunglasses"] },
  { e: "😍", k: ["love", "hearteyes"] },
  { e: "😘", k: ["kiss"] },
  { e: "🥰", k: ["love"] },
  { e: "😗", k: ["kiss"] },
  { e: "🤩", k: ["star", "starstruck"] },
  { e: "🤔", k: ["thinking", "hmm"] },
  { e: "🤨", k: ["raised", "brow"] },
  { e: "😐", k: ["neutral"] },
  { e: "😑", k: ["expressionless"] },
  { e: "😶", k: ["nomouth", "silent"] },
  { e: "😏", k: ["smirk"] },
  { e: "😒", k: ["unamused"] },
  { e: "🙄", k: ["roll", "eyes"] },
  { e: "😬", k: ["grimace"] },
  { e: "🤥", k: ["lying"] },
  { e: "😌", k: ["relieved"] },
  { e: "😔", k: ["pensive", "sad"] },
  { e: "😪", k: ["sleepy"] },
  { e: "🤤", k: ["drool"] },
  { e: "😴", k: ["sleep"] },
  { e: "😷", k: ["mask", "sick"] },
  { e: "🤒", k: ["sick", "thermometer"] },
  { e: "🤕", k: ["hurt"] },
  { e: "🤧", k: ["sneeze"] },
  { e: "🥶", k: ["cold", "freeze"] },
  { e: "🥵", k: ["hot"] },
  { e: "🥴", k: ["woozy"] },
  { e: "😵", k: ["dizzy"] },
  { e: "🤯", k: ["mind", "blown"] },
  { e: "🤠", k: ["cowboy"] },
  { e: "🥳", k: ["party"] },
  { e: "😢", k: ["cry", "sad"] },
  { e: "😭", k: ["sob", "cry"] },
  { e: "😤", k: ["huff"] },
  { e: "😠", k: ["angry"] },
  { e: "😡", k: ["rage", "angry"] },
  { e: "🤬", k: ["swear", "censor"] },
  { e: "😱", k: ["scream", "shock"] },
  { e: "😨", k: ["fear"] },
  { e: "😰", k: ["anxious"] },
  { e: "😥", k: ["sad", "relieved"] },
  { e: "😓", k: ["sweat"] },
  { e: "🤗", k: ["hug"] },
  { e: "🤭", k: ["giggle"] },
  { e: "🤫", k: ["shh", "quiet"] },
  { e: "🤐", k: ["zip"] },
  { e: "🥺", k: ["pleading"] },
  { e: "😈", k: ["devil"] },
  { e: "👿", k: ["devil", "angry"] },
  { e: "💀", k: ["skull", "dead"] },
  { e: "👻", k: ["ghost"] },
  { e: "👽", k: ["alien"] },
  { e: "🤖", k: ["robot"] },
  { e: "🎃", k: ["pumpkin"] },
  // Hand gestures
  { e: "👍", k: ["thumbsup", "yes", "good"] },
  { e: "👎", k: ["thumbsdown", "no", "bad"] },
  { e: "👌", k: ["ok"] },
  { e: "🤌", k: ["pinched"] },
  { e: "🤏", k: ["pinch", "small"] },
  { e: "✌️", k: ["peace", "victory"] },
  { e: "🤞", k: ["fingers", "crossed"] },
  { e: "🤟", k: ["love", "ily"] },
  { e: "🤘", k: ["rock", "horns"] },
  { e: "🤙", k: ["call"] },
  { e: "👈", k: ["pointleft"] },
  { e: "👉", k: ["pointright"] },
  { e: "👆", k: ["pointup"] },
  { e: "👇", k: ["pointdown"] },
  { e: "🖕", k: ["middle"] },
  { e: "✋", k: ["hand", "stop"] },
  { e: "🖐️", k: ["hand", "five"] },
  { e: "🖖", k: ["vulcan"] },
  { e: "👋", k: ["wave", "hi"] },
  { e: "🤝", k: ["handshake"] },
  { e: "🙏", k: ["pray", "thanks"] },
  { e: "👏", k: ["clap"] },
  { e: "🙌", k: ["raised", "praise"] },
  { e: "🤲", k: ["palms"] },
  { e: "💪", k: ["muscle", "strong"] },
  // Hearts & celebration
  { e: "❤️", k: ["heart", "love"] },
  { e: "🧡", k: ["heart", "orange"] },
  { e: "💛", k: ["heart", "yellow"] },
  { e: "💚", k: ["heart", "green"] },
  { e: "💙", k: ["heart", "blue"] },
  { e: "💜", k: ["heart", "purple"] },
  { e: "🖤", k: ["heart", "black"] },
  { e: "🤍", k: ["heart", "white"] },
  { e: "💔", k: ["heart", "broken"] },
  { e: "❣️", k: ["heart"] },
  { e: "💕", k: ["hearts"] },
  { e: "💖", k: ["heart", "sparkle"] },
  { e: "💘", k: ["heart", "arrow"] },
  { e: "💝", k: ["gift", "heart"] },
  { e: "✨", k: ["sparkles", "shiny"] },
  { e: "⭐", k: ["star"] },
  { e: "🌟", k: ["star", "glow"] },
  { e: "💫", k: ["dizzy"] },
  { e: "💥", k: ["boom", "bang"] },
  { e: "🔥", k: ["fire", "lit"] },
  { e: "🎉", k: ["party", "tada"] },
  { e: "🎊", k: ["confetti"] },
  { e: "🎁", k: ["gift"] },
  { e: "🎂", k: ["cake", "birthday"] },
  // Tech / objects
  { e: "✅", k: ["check", "done", "yes"] },
  { e: "❌", k: ["cross", "no", "wrong"] },
  { e: "⚠️", k: ["warning"] },
  { e: "❓", k: ["question"] },
  { e: "❗", k: ["exclamation"] },
  { e: "💯", k: ["hundred", "100"] },
  { e: "💢", k: ["anger"] },
  { e: "💤", k: ["zzz", "sleep"] },
  { e: "💬", k: ["speech", "chat"] },
  { e: "🗯️", k: ["angry", "speech"] },
  { e: "💭", k: ["thought"] },
  { e: "🚀", k: ["rocket", "ship"] },
  { e: "🌈", k: ["rainbow"] },
  { e: "☀️", k: ["sun"] },
  { e: "🌙", k: ["moon"] },
  { e: "⚡", k: ["zap", "lightning"] },
  { e: "❄️", k: ["snow", "snowflake"] },
  { e: "👑", k: ["crown", "king"] },
  { e: "💎", k: ["gem"] },
  { e: "🏆", k: ["trophy", "win"] },
  { e: "🥇", k: ["gold", "medal"] },
  { e: "🥈", k: ["silver"] },
  { e: "🥉", k: ["bronze"] },
  { e: "👀", k: ["eyes"] },
  { e: "🍀", k: ["clover", "luck"] },
  { e: "☕", k: ["coffee"] },
  { e: "🍕", k: ["pizza"] },
  { e: "🍔", k: ["burger"] },
  { e: "🍺", k: ["beer"] },
  { e: "🍷", k: ["wine"] },
  { e: "🌸", k: ["blossom"] },
  { e: "🐶", k: ["dog"] },
  { e: "🐱", k: ["cat"] },
];

export function searchEmojis(query: string, max = 80): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return EMOJI_CATALOG.slice(0, max);
  const out: EmojiEntry[] = [];
  for (const entry of EMOJI_CATALOG) {
    if (entry.k.some((kw) => kw.includes(q))) out.push(entry);
    if (out.length >= max) break;
  }
  return out;
}
